# -*- Mode: Python -*- vi:si:et:sw=4:sts=4:ts=4:syntax=python
from cerbero.errors import ConfigurationError

class Recipe(recipe.Recipe):
    name = 'pitivi'
    version = '0.95'
    licenses = [License.GPLv2Plus]
    remotes = {'origin': 'git://git.gnome.org/pitivi'}
    config_sh = 'sh ./autogen.sh --noconfigure && ./configure'
    configure_options = "--disable-help"
    commit = 'origin/master'
    deps = ['gst-editing-services-1.0',
            'gst-python-1.0',
            'gst-libav-1.0',
            'gst-plugins-bad-1.0',
            'gst-plugins-ugly-1.0',
            'gst-transcoder',
            'numpy',
            'matplotlib',
            'adwaita-icon-theme',
            'shared-mime-info'] # brings in gtk+

    files_libs = ['libpitivi-1.0']
    files_typelibs = [
        'Pitivi-1.0',
    ]
    use_system_libs = True
    files_bins = ['pitivi']
    files_lang = ['pitivi']
    files_pitivi = ['lib/pitivi/python/pitivi',
                    'share/pitivi/',
                    'share/applications/pitivi.desktop']

    def configure(self):
        if not self.config.variants.gi:
            raise FatalError(_("GObject-Introspection support is required for pitivi"))
        super(Recipe, self).configure()
